site_name: HEW AI-assistant
site_description: "Ethiopian HEW AI-assistant Documentation"
site_url: https://localhost:8001
theme:
  name: material
  font:
    text: "Inter"
    code: "Roboto Mono"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    - navigation.indexes
    - navigation.top
nav:
  - Home:
    - index.md
    - Getting Started: getting-started.md
  - Key features:
    - Components: components/index.md
    - Question-Answering: components/chat.md
    - Document Management: components/doc-management.md
  - Contribute:
    - Setup: contribute/dev-setup.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: On this page
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - glightbox
  - search
  - blog:
      post_excerpt: required
  - open-in-new-tab
