services:
  backend:
    image: idinsight/hew-ai-backend:latest
    build:
      context: ../../backend
      dockerfile: Dockerfile
    command: >
      /bin/sh startup.sh
    restart: always
    volumes:
      - temp:/usr/src/backend/temp
    env_file:
      - .base.env
      - .backend.env
    environment:
      - CHAINLIT_AUTH_SECRET=.4=P6SnNr*P0sf~gzV>tq0*eZ7NoxeVyN50lN_%hVmxF%?wI3OUDV%0p8MsD9jrq
    ports: # Expose backend port
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: ../../backend
  chainlit-app:
    build:
      context: ../../chainlit_app
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    develop:
      watch:
        - action: rebuild
          path: ../../chainlit_app
volumes:
  temp:
