services:
  backend:
    image: idinsight/hew-ai-backend:latest
    build:
      context: ../../backend
      dockerfile: Dockerfile
    command: >
      /bin/sh startup.sh
    restart: always
    volumes:
      - temp:/usr/src/backend/temp
    env_file:
      - .base.env
      - .backend.env
    ports: # Expose backend port
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: ../../backend
  chainlit-app:
    build:
      context: ../../chainlit
      dockerfile: Dockerfile.chainlit
    ports:
      - "8100:8100"
    volumes:
      - .:/app  # Mount your project folder
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - API_URL=http://backend:8000
volumes:
  temp:
