"""Add feedback table

Revision ID: 5c56714fdbad
Revises: 8e185a868bcc
Create Date: 2024-11-05 14:36:17.367872

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c56714fdbad"
down_revision: Union[str, None] = "8e185a868bcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("feedback_id", sa.UUID(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column("feedback_text", sa.String(), nullable=False),
        sa.Column("like", sa.Boolean(), nullable=False),
        sa.Column("created_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    # ### end Alembic commands ###
