"""added chat history columns

Revision ID: 7cf772c80477
Revises: 0ac7e03fe00d
Create Date: 2024-11-11 13:07:55.872778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cf772c80477"
down_revision: Union[str, None] = "0ac7e03fe00d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_requests", sa.Column("messages_original", sa.String(), nullable=True)
    )
    op.add_column(
        "chat_requests", sa.Column("session_summary", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_requests", "session_summary")
    op.drop_column("chat_requests", "messages_original")
    # ### end Alembic commands ###
