"""Create document table

Revision ID: e47b5a406d2e
Revises: 
Create Date: 2024-10-10 12:38:50.675593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

from app.config import (
    PGVECTOR_DISTANCE,
    PGVECTOR_EF_CONSTRUCTION,
    PGVECTOR_M,
    PGVECTOR_VECTOR_SIZE
)

# revision identifiers, used by Alembic.
revision: str = 'e47b5a406d2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;") 
    op.create_table('documents',
                    sa.Column('uuid', sa.UUID(), nullable=False),
                    sa.Column('file_name', sa.String(length=255), nullable=False),
                    sa.Column('chunk_id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('embedding_vector', pgvector.sqlalchemy.Vector(dim=PGVECTOR_VECTOR_SIZE), 
                            nullable=False),
                    sa.Column('created_datetime_utc', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_datetime_utc', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('uuid')
    )
    op.execute(
        f"""CREATE INDEX document_idx ON documents
        USING hnsw (embedding_vector {PGVECTOR_DISTANCE})
        WITH (m = {PGVECTOR_M}, ef_construction = {PGVECTOR_EF_CONSTRUCTION})"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_index(
        "document_idx",
        table_name="documents",
        postgresql_using="hnsw",
        postgresql_with={
            "M": {PGVECTOR_M},
            "ef_construction": {PGVECTOR_EF_CONSTRUCTION},
        },
        postgresql_ops={"embedding": {PGVECTOR_DISTANCE}},
    )
    op.drop_table("documents")
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
