"""Add is_active field to documents db

Revision ID: 970ae3c2a1b4
Revises: 5c56714fdbad
Create Date: 2024-11-15 16:23:26.813941

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "970ae3c2a1b4"
down_revision: Union[str, None] = "0ac7e03fe00d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("is_archived", sa.Boolean(), nullable=True))
    op.execute("UPDATE documents SET is_archived = FALSE")  # for existing rows
    op.alter_column("documents", "is_archived", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "is_archived")
    # ### end Alembic commands ###
