"""added query db

Revision ID: 500c85763aca
Revises:
Create Date: 2024-10-10 14:42:21.064218

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "500c85763aca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query",
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("query_metadata", sa.String(), nullable=True),
        sa.Column("query_text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("query_id"),
    )
    op.create_index(op.f("ix_query_query_id"), "query", ["query_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_query_id"), table_name="query")
    op.drop_table("query")
    # ### end Alembic commands ###
