name: Python Linting
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "**.py"

jobs:
  python-lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            backend/requirements.txt
            requirements-dev.txt

      - run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r requirements-dev.txt

      - name: Run MyPy
        run: |
          mypy backend/app
        env:
          POSTGRES_USER: postgres-test-user
          POSTGRES_PASSWORD: postgres-test-pw
          POSTGRES_DB: postgres-test-db
          REDIS_HOST: redis://redis:6379
          POSTGRES_HOST: postgres

      - name: Run ruff
        run: |
          ruff check .
        env:
          POSTGRES_USER: postgres-test-user
          POSTGRES_PASSWORD: postgres-test-pw
          POSTGRES_DB: postgres-test-db
          REDIS_HOST: redis://redis:6379
          POSTGRES_HOST: postgres

      - name: Check code formatting with Black
        run: |
          cd backend
          black --check .
